name: Copie du README vers Q1_archive_README

on:
  push:
    branches:
      - main

jobs:
  copy-readme:
    runs-on: ubuntu-latest

    steps:
      # Vérifiez le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Copier le contenu de README.md dans Q1_archive_README.md
      - name: Create Q1_archive_README.md
        run: |
          cp README.md Q1_archive_README.md

      # Configurer Git pour pousser les modifications
      - name: Configure Git
        run: |
          git config user.name "Frizoks"
          git config user.email "luc.lecarpentier5@gmail.com"

      # Ajouter et pousser Q1_archive_README.md vers le dépôt
      - name: Push Q1_archive_README.md
        run: |
          git add Q1_archive_README.md
          git commit -m "Add Q1_archive_README.md"
          git push
