name: Q1_archive_README

on: [push]
permissions:
  contents: write

jobs:
  copy-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Q1_archive_README.md
        run: |
          cp README.md Q1_archive_README.md

      - name: Configure Git
        run: |
          git config user.name "Frizoks"
          git config user.email "luc.lecarpentier5@gmail.com"

      - name: Push Q1_archive_README.md
        run: |
          git add Q1_archive_README.md
          git commit -m "Add Q1_archive_README.md"
          git push
